addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.5.0")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.0.0")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.4.2")
addSbtPlugin("de.heikoseeberger"   % "sbt-header"      % "5.6.0")
addSbtPlugin("org.xerial.sbt"      % "sbt-sonatype"    % "3.9.5")
addSbtPlugin("com.typesafe.sbt"    % "sbt-git"         % "1.0.0")
addSbtPlugin("com.jsuereth" % "sbt-pgp" % "1.1.2")
addSbtPlugin("com.geirsson" % "sbt-ci-release" % "1.5.7")
